casangi/xradio

tests/unit/test_image.py

more tests to verify images are identical at casacore_im1 -> xds -> casacore_im2 by comparing metadata for the two  casacore images

add casacore image metadata test for casacore -> xds -> casacore

---

src/xradio/vis/convert_msv2_to_processing_set.py

Changes that need to support variable field direction reference. If reference varies with FIELD rows, the table should have PhaseDir_Ref, DelayDir_Ref, and RefDir_Ref columns that hold direction reference frame for PHASE_DIR, DELAY_DIR, REFERENCE_DIR, respectively (this is not indicated in the MSv2 schema but it seems that importasdm task creates *_Ref columns if necessary). Changes proposed here read these columns if they exist, instead of extracting reference from column keywords.

support variable field direction ref

---

src/xradio/vis/_vis_utils/_ms/partition_queries.py

Don't make assumptions on the values in the STATE_ID column if the STATE table is empty; simply don't select on STATE_ID in the taql query in this case.

Better handling of empty STATE table

---

src/xradio/image/_util/_zarr/common.py

Apparently Mac M1 does not have these types (probably because it's a 64-bit system).
For reference I'm running on mac M1, python 3.12, numpy 1.26.3.

Work around missing np.float128 and np.complex256

---

src/xradio/vis/_vis_utils/_ms/_tables/load_main_table.py
src/xradio/vis/_vis_utils/_ms/_tables/read.py
src/xradio/vis/_vis_utils/_ms/_tables/read_main_table.py
src/xradio/vis/_vis_utils/_ms/_tables/read_subtables.py
src/xradio/vis/_vis_utils/_ms/chunks.py
src/xradio/vis/_vis_utils/_ms/conversion.py
src/xradio/vis/_vis_utils/_ms/descr.py
src/xradio/vis/_vis_utils/_ms/optimised_array_operations.py
src/xradio/vis/_vis_utils/_ms/optimised_functions.py
src/xradio/vis/_vis_utils/_ms/partition_queries.py
tests/unit/vis/_vis_utils/_ms/test_optimised_functions.py

The function to get (unique) baselines has been optimised, reducing the computation time from 45s to 0.8s for a 71G LOFAR MeasurementSet. In addition, the function now returns a 2D array of antenna pairs, representing baselines, instead of using strings. The pairing functions used in this function have been added with tests, and a new function has been added to get baseline indices, which is also an optimisation. A function has also been added to get unique values of 1D arrays, which is around 3x faster on average relative the the NumPy method.

Performance Improvements of Unique Baselines and Baseline Indices

---

src/xradio/image/_util/_casacore/common.py
src/xradio/image/_util/_casacore/xds_to_casacore.py
tests/unit/test_image.py

root cause seems to be that standard python has no single precision floating point type. So, I had to write a bit of a kludge depending if I want single precision pixels or another type of pixels in the image.

120 fix writing of casa images

---

src/xradio/_utils/zarr/common.py
src/xradio/image/_util/zarr.py
src/xradio/image/image.py
src/xradio/vis/load_processing_set.py
tests/unit/test_image.py

Move_load_no_dask_zarr() and helper  _get_attrs() from vis/load_processing_set.py  to _utils/zarr/common.py 
load_image() now uses _load_no_dask_zarr() wrapped in image specific code (read history xds attr, decode encoded dicts back to numpy arrays, etc) to read data and avoids creating a DAG.

145 load image function is creating a dag when opening a imgzarr file

---

src/xradio/vis/_vis_utils/_ms/_tables/read.py

For further information, see https://github.com/casangi/xradio/issues/152.

Mitigation for https://github.com/casacore/python-casacore/issues/130

---

src/xradio/vis/_vis_utils/_ms/_tables/load.py
src/xradio/vis/_vis_utils/_ms/_tables/load_main_table.py
src/xradio/vis/_vis_utils/_ms/_tables/read.py
src/xradio/vis/_vis_utils/_ms/_tables/read_main_table.py
src/xradio/vis/_vis_utils/_ms/_tables/read_subtables.py
src/xradio/vis/_vis_utils/_ms/_tables/write.py
src/xradio/vis/_vis_utils/_ms/_tables/write_exp_api.py
src/xradio/vis/_vis_utils/_ms/chunks.py
src/xradio/vis/_vis_utils/_ms/conversion.py
src/xradio/vis/_vis_utils/_ms/descr.py
src/xradio/vis/_vis_utils/_ms/msv4_sub_xdss.py
src/xradio/vis/_vis_utils/_ms/optimised_functions.py
src/xradio/vis/_vis_utils/_ms/partition_queries.py
src/xradio/vis/_vis_utils/_ms/partitions.py
src/xradio/vis/_vis_utils/_ms/subtables.py
src/xradio/vis/_vis_utils/_utils/partition_attrs.py
src/xradio/vis/_vis_utils/_utils/xds_helper.py
src/xradio/vis/_vis_utils/_zarr/read.py
src/xradio/vis/_vis_utils/_zarr/write.py
src/xradio/vis/_vis_utils/ms.py
src/xradio/vis/_vis_utils/zarr.py
src/xradio/vis/vis_io.py

This is an uneventful PR. It simply converts the docstring syntax, from the old reST to numpy style in src/vis.
I run `pyment` and then corrected manually a few formatting issues plus a few small bugs in the docs that came up in the process. Finally run black on the files changed to catch up with the changes in some type annotations.  
Note for the future: in these changes, the types of parameter/returns are included in the docstrings. But for the future I'd favor not including types manually in the docstrings. I think it would be easier to maintain if we use the types directly from the type hints via extensions (for our case `[sphinx-autodoc-napoleon-typehints](https://pypi.org/project/sphinx-autodoc-napoleon-typehints)). This way we can get the types auto-populated in the documentation …

Convert docstrings to numpy style (in vis)

---

.github/workflows/python-testing-macos.yml
pyproject.toml
tests/unit/vis/_vis_utils/_ms/_tables/test_read.py

The failure is harmless in principle I think. Here is an attempt to fix the test without removing it. 
The failure is a manifestation of https://github.com/numpy/numpy/issues/21166 "Conversion of numpy.nan to int gives inconsistent results" causing different behavior between platforms, for example: https://github.com/aai-institute/pyDVL/issues/474
This discrepancy should not be a big deal but could bite us if we end up having integer data variables in the final schema.
For example missing "time-baseline" rows in the MS, become "np.nan" values in xdss, with the caveat that for integer data variables they would get whatever special value an np.nan is converted to. It turns out that:
- on linux, nan converted to int32 => -2147483648
- on linux, nan converted to int64 => -9223372036854775808 …

Fix  test_get_pad_nan_feed1 error on MacOS

---

src/xradio/vis/_vis_utils/_ms/_tables/read.py
src/xradio/vis/_vis_utils/_ms/subtables.py
src/xradio/vis/_vis_utils/_utils/xds_helper.py
tests/unit/vis/_vis_utils/_ms/_tables/test_read.py
tests/unit/vis/_vis_utils/_utils/test_xds_helper.py
tests/unit/vis/conftest.py

Fixes warnings triggered in vis unit tests.
Most of the warnings had to do with casts or with deprecated operations on pandas indices.
---
Note well:
```
```

Fix warnings triggered in vis tests

---

src/xradio/vis/_vis_utils/_ms/_tables/read.py

Refactor read_col_conversion() to prevent storing two copies of a MeasurementSet column in memory. Reduces memory consumption by ~>40% and has a small ~5% improvement in wall time

Optimisation: Remove full column copy when reshaping

---

src/xradio/vis/_vis_utils/_ms/_tables/read.py
src/xradio/vis/_vis_utils/_ms/_tables/read_main_table.py
tests/unit/vis/_vis_utils/test_ms.py

With this xradio can read/convert all MSs from CASA's casatestdata and stakeholder tests.
Fixes #185.
Note well:
```
```

Small fixes for corner case MSs from casatestdata

---

src/xradio/vis/_vis_utils/_ms/msv2_to_msv4_meta.py

Idea here is that we map to `astropy` arguments, which are typically lower case.
Also clean the conversion code up a bit more... It confused me quite a bit initially :)

Fix reference frame conversion

---

src/xradio/vis/_processing_set.py
src/xradio/vis/read_processing_set.py

Changed frequency spw attribute name in processing_set._get_ps_freq_axis from "spw_id" to "spectral_window_id"
Also removed print(xds) line in read_processing_set.
Test failures due to not failures downloading test ms/table (?)

Fix processing set freq axis, remove debugging output

---

src/xradio/vis/_vis_utils/_ms/conversion.py
src/xradio/vis/convert_msv2_to_processing_set.py

This commit aligns number of digit for ms_v4_id.
If number of partitions is 11, for example, name of the msv4 will change from "ps_name_0" to "ps_name_00", etc.
That affects sort order of the msv4 on disk. Previously, it was like the following.
```
ps_name_0
ps_name_1
ps_name_10
ps_name_2
...
ps_name_9
```
After this change, the order will be more intuitive.
```
ps_name_00
ps_name_01
ps_name_02
...
ps_name_09
ps_name_10
```

Processing set name formatting

---

src/xradio/measurement_set/_utils/_msv2/conversion.py
src/xradio/measurement_set/_utils/_msv2/msv4_info_dicts.py
src/xradio/measurement_set/schema.py
tests/stakeholder/test_measure_set_stakeholder.py

Resolves #327.
---
Note well:
```
```

Add optional partition_info/antenna_name

---

src/xradio/measurement_set/_utils/_msv2/conversion.py
src/xradio/measurement_set/_utils/_msv2/msv4_info_dicts.py
src/xradio/measurement_set/_utils/_msv2/msv4_sub_xdss.py
src/xradio/measurement_set/processing_set.py
src/xradio/measurement_set/schema.py

Resolves #333.
---
Note well:
```
```

VisibilityXds (and SpectrumXds): scan_number (int) => scan_name (str)

---

src/xradio/measurement_set/load_processing_set.py
tests/unit/measurement_set/test_load_processing_set.py

New test script test_load_processing_set.py to test load_processing_set. The tests found that a small change is needed in line 184 of load_processing_set. If you prefer we can separate the fix in the code from the tests.
All tests pass locally and in the workflow actions.
These new tests increase the coverage of that module from 31.25% to 90.63%.

419 create unit tests for load processing set

---

src/xradio/measurement_set/_utils/_msv2/conversion.py
tests/stakeholder/test_measure_set_stakeholder.py

New version of #423, because I could not rebase onto main / merge main into it without losing most of the code changes.
Credit goes to @sstansill for the original changes:
- Fixes a crash when converting a dataset without WEIGHT_SPECTRUM using `parallel_mode="time"`, where the chunking pattern in frequency would be incorrect.
- Use `dask.array.tile()` instead of `np.tile()` when using `parallel_mode="time"`. This ensures WEIGHT and WEIGHT_SPECTRUM columns aren't eagerly computed eagerly, reducing memory usage.
- Use `read_col_conversion_dask()` only on large columns, this improves performance.
I've refactored and simplified `create_date_variables()` along the way:
- Remove all-encompassing `if` statement inside main loop that was checking for the presence of WEIGHT + WEIGHT_SPECTRUM, …

read_col_conversion fixes
