casangi/xradio

- src/xradio/vis/convert_msv2_to_processing_set.py
It is based on the meeting at NAOJ with Jan-Willem
> added an item into col_to_data_variable_names for SD data converting

- src/xradio/image/_util/_fits/xds_from_fits.py
- src/xradio/image/_util/common.py
Addresses part of #155
1. Since doppler is expected, default set it to `RADIO`
2. Move variable `cunit` out of call to `_get_freq_values`
3. Add `FREQ` to _get_transpose_list option
4. Address minor typos
Any comments on point 1?
Let me know if this is fine, I'll be happy to changes based on your suggestions
> Fix issues in read_image when opening FITS

- .github/workflows/black.yml
- Makefile
- doc/source/conf.py
- pyproject.toml
- src/xradio/schema/typing.py
- tests/stakeholder/test_vis_stakeholder.py
- tests/unit/vis/_vis_utils/_ms/_tables/test_read_main_table.py
- tests/unit/vis/_vis_utils/_ms/_tables/test_read_subtables.py
- tests/unit/vis/_vis_utils/_ms/test_chunks.py
- tests/unit/vis/_vis_utils/_ms/test_conversion.py
- tests/unit/vis/_vis_utils/_ms/test_descr.py
- tests/unit/vis/_vis_utils/_ms/test_partitions.py
- tests/unit/vis/_vis_utils/_ms/test_subtables.py
- tests/unit/vis/_vis_utils/_utils/test_cds.py
- tests/unit/vis/_vis_utils/_zarr/test_read.py
- tests/unit/vis/_vis_utils/_zarr/test_write.py
- tests/unit/vis/_vis_utils/test_ms.py
- tests/unit/vis/conftest.py
- tests/unit/vis/ms_test_utils/cds_checks.py
This applies black to some more Python files. Also attempt to make it a bit easier to apply and check code formatting.
> Blackify tests & documentation

- src/xradio/vis/_vis_utils/_ms/_tables/read.py
Fixes #197, see issue for the current fix in this branch/PR.
Note that there might be additional nuances to consider (see issue comments), but at least this should prevent the issue of missing variables.
---
Note well:
```
```
> Fix the issue in read_generic_table with columns that have "empty" cells

- doc/source/vis_schema.rst
- src/xradio/vis/_vis_utils/_ms/create_antenna_xds.py
- src/xradio/vis/_vis_utils/_ms/create_field_and_source_xds.py
- src/xradio/vis/_vis_utils/_ms/msv4_sub_xdss.py
- src/xradio/vis/schema.py
Fixes #226.
Follow up to update antenna_id=>antenna_name in main_xds and other xdss follows in #235, but this PR already has an updated version of antenna_xds
---
Note well:
```
```
> Populate schema and doc tables for antenna_xds, weather_xds, system_calibration_xds + partition_info

- pyproject.toml
- src/xradio/vis/_vis_utils/_ms/_tables/read.py
Note: this branch includes the branch from #243, which would need to be merged first.
Fixes #242 and un-specifies the numpy version in pyproject.toml.
---
Note well:
```
```
> Fix issues with numpy 2 and POLARIZATION/CORR_TYPE (and other variable size cols)

- docs/source/correlated_data/schema_and_api/correlated_data_schema.rst
- docs/source/xradio_sphinx/schema_table.py
- src/xradio/_utils/common.py
- src/xradio/_utils/schema.py
- src/xradio/correlated_data/__init__.py
- src/xradio/correlated_data/_utils/_ms/conversion.py
- src/xradio/correlated_data/_utils/_ms/create_antenna_xds.py
- src/xradio/correlated_data/_utils/_ms/create_field_and_source_xds.py
- src/xradio/correlated_data/_utils/_ms/msv4_sub_xdss.py
- src/xradio/correlated_data/schema.py
- tests/stakeholder/test_correlated_stakeholder.py
Resolved #264, see issue comments for more details, especially on measures and their allowed frames, coordinate systems, etc.
---                                                                                                                                                                                                                                                           
Note well:                                                                                                                                                                                                                                                    
``` …
```
> Extend schema to check explicit literal values in quantities and measures + rename of main schema class to `VisibilityXds` + `SpectrumXds`

- src/xradio/correlated_data/_utils/_ms/msv4_sub_xdss.py
Fixes #265.
---                                                                                                                                                                                                                                                           
Note well:                                                                                                                                                                                                                                                    
```                                                                                                                                                                                                                                                           
This contribution is …
```
> CASAguides dataset ngc3256_line_target.ms error - correct issues in dimensions in generic sys_cal_xds,

- src/xradio/correlated_data/_utils/_ms/create_field_and_source_xds.py
Fixes #266, when the field table refers to source IDs missing from the source table, those are filled in the source_xds.
---
Note well:
```
(c) European Southern Observatory, 2024 
```
> Pad missing sources as "Unknown"/nan (CASAguide twhya_calibrated.ms failures)

- docs/source/measurement_set/schema_and_api/measurement_set_schema.rst
- src/xradio/_utils/schema.py
- src/xradio/measurement_set/_utils/_msv2/conversion.py
- src/xradio/measurement_set/_utils/_msv2/create_field_and_source_xds.py
- src/xradio/measurement_set/_utils/_msv2/msv4_sub_xdss.py
- src/xradio/measurement_set/schema.py
- src/xradio/sphinx/schema_table.py
Fixes #282.
This updates the measures and also includes a few more fixes/improvements to the schema and docs.
---
Note well:
```
(c) European Southern Observatory, 2024 
```
> Update schema and converter to align measures and get them as close as possible to astropy conventions + more schema and doc fixes and improvements

- src/xradio/measurement_set/processing_set.py
- tests/stakeholder/test_measure_set_stakeholder.py
Fixes #299 
---
Note well:
```
(c) European Southern Observatory, 2024 
```
> Fix error in `get_ps_freq_axis()`, with outdate frame key

- src/xradio/measurement_set/_utils/_msv2/conversion.py
- src/xradio/measurement_set/_utils/_msv2/msv4_sub_xdss.py
- src/xradio/measurement_set/schema.py
Fixes MSv4 review issue #338.
---
Note well:
```
```
> SystemCalibrationXds: make receptor_label string, add polarization_type

- docs/source/measurement_set/schema_and_api/measurement_set_schema.rst
- src/xradio/measurement_set/_utils/_msv2/conversion.py
- src/xradio/measurement_set/_utils/_msv2/msv4_sub_xdss.py
- src/xradio/measurement_set/schema.py
Resolves #335.
---
Note well:
```
```
> SystemCalibrationXds: rename time_cal => time_system_cal, frequency_cal => frequency_system_cal

- src/xradio/measurement_set/schema.py
Closes #353.
---
Note well:
```
```
> AntennaXds: Additional mount types (ALT-AZ+BWG)

- src/xradio/_utils/dict_helpers.py
- src/xradio/image/_util/_casacore/xds_from_casacore.py
- src/xradio/image/_util/_fits/xds_from_fits.py
- src/xradio/image/_util/common.py
Support PC01_01 etc keywords in FITS headers. Unify beam handling.
> Support PC01_01 etc keywords in FITS headers.

- src/xradio/measurement_set/_utils/_msv2/create_field_and_source_xds.py
Fixes #391.
---
Note well:
```
```
> Fix warnings in MS stakeholder tests

- CONTRIBUTOR_LICENSING_AGREEMENT_ESO.txt
- CONTRIBUTOR_LICENSING_AGREEMENT_EXCEPTION.txt
Updates CLA related files according to the "Agreement on the Use and Licensing of the ALMA Data Processing Software" and follow-up discussions.
> Replace CLA_EXCEPTION.txt => CLA_ESO.txt

- src/xradio/image/_util/_casacore/xds_from_casacore.py
- src/xradio/image/_util/_casacore/xds_to_casacore.py
- src/xradio/image/_util/_fits/xds_from_fits.py
- tests/unit/test_image.py
Would be helpful if a new release could be made for this fix.
> 403 wave unit and casacore image analog sometimes has wrong form when readingwriting

- src/xradio/measurement_set/_utils/_msv2/msv4_sub_xdss.py
- src/xradio/measurement_set/schema.py
> Renamed 'undimensioned' unit to 'dimensionless'

- src/xradio/measurement_set/_utils/_msv2/_tables/read.py
- src/xradio/measurement_set/_utils/_msv2/conversion.py
- tests/stakeholder/test_measure_set_stakeholder.py
> Fix TIME_CENTROID values (were in seconds since 1858 11 17)

- src/xradio/measurement_set/_utils/_msv2/conversion.py
> Do not add (old) attr effective_integration_time

- src/xradio/measurement_set/_utils/_msv2/_tables/read.py
- src/xradio/measurement_set/_utils/_msv2/create_antenna_xds.py
- src/xradio/measurement_set/_utils/_msv2/msv4_sub_xdss.py
- tests/stakeholder/test_measure_set_stakeholder.py
> Fix time values in secondary datasets: pointing, weather, sys_cal

- src/xradio/measurement_set/measurement_set_xdt.py
- src/xradio/measurement_set/processing_set_xdt.py
- tests/unit/measurement_set/_utils/_msv2/test_conversion.py
- tests/unit/measurement_set/conftest.py
- tests/unit/measurement_set/test_processing_set_xdt.py
> Fix exception using xr_ps.query on data group after another query

- src/xradio/measurement_set/_utils/_msv2/create_field_and_source_xds.py
- src/xradio/measurement_set/processing_set_xdt.py
> xr.concat join default value: xarray FutureWarning in processing_set_xdt

- tests/stakeholder/test_image_stakeholder.py
- tests/stakeholder/test_measure_set_stakeholder.py
- tests/unit/measurement_set/conftest.py
This fixes the wrong data type usage in the tests that include toolviper's download function.
> 471 fix data type used in tests with toolviper download
